VMS.Web/Controllers/Add_ServiceController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VMS.DAL.Infrastructure;
using VMS.Entities;
using VMS.Models;

namespace VMS.Web.Controllers
{
    public class Add_ServiceController : Controller
    {


        private UnitOfWork unitOfWork = new UnitOfWork();
        // GET: Add_Service
        public ActionResult Index()
        {
           
           var vendor = new Vendor();
           var service_category = new ServiceCategory();
           var service_type = new ServiceType();
           var approver1 = new User();
           var userDepartmenttype = new ServiceUserDepartment();
         


            ViewBag.vendorList = unitOfWork.DepartmentRepository.Get(vendor, null);
            ViewBag.serviceCategoryList = unitOfWork.DepartmentRepository.Get(service_category, 0);
            ViewBag.serviceTypeList = unitOfWork.DepartmentRepository.Get(service_type, 0);
            ViewBag.firstLevelApproverList = unitOfWork.DepartmentRepository.Get(approver1, "Approver1",null);
            ViewBag.secondLevelApproverList = unitOfWork.DepartmentRepository.Get(approver1, "Approver2",null);
            ViewBag.thirdLevelApproverList = unitOfWork.DepartmentRepository.Get(approver1, "Approver3", null);
            ViewBag.userDepartment = unitOfWork.DepartmentRepository.Get(userDepartmenttype, 0);
            ViewBag.serviceCode = unitOfWork.DepartmentRepository.auto_generatedCode();
            return View();
        }

        

        [HttpPost]
       
        public ActionResult Index(VMSEntity add_service)
          {
            
            

                var service = Mapper.Map<VMSEntity, Service>(add_service);
                var service_user = Mapper.Map<VMSEntity, ServiceUser>(add_service);
                var service_vendor = Mapper.Map<VMSEntity, ServiceVendor>(add_service);

                unitOfWork.DepartmentRepository.Insert(service);

                unitOfWork.DepartmentRepository.Insert(service_user);

                unitOfWork.DepartmentRepository.Insert(service_vendor);
                unitOfWork.Save();
         
            return RedirectToAction("Create", "Add_POReport", new {service_code = add_service.serviceCode, vendor_Id = add_service.vendorId });
        }

        [HttpGet]
        public JsonResult GetApproverdata(int count)
        {


            // string service_Code = serviceCode;
            var approver1 = new User();

            var firstLevelApproverList = unitOfWork.DepartmentRepository.Get(approver1, "Approver1", count);
            var secondLevelApproverList = unitOfWork.DepartmentRepository.Get(approver1, "Approver2", count);
            var thirdLevelApproverList = unitOfWork.DepartmentRepository.Get(approver1, "Approver2", count);



            //var sprintJson = "{\"FirstLevelApprover\":\"" + firstLevelApproverList + "\",\"SecondLevelApprover\":" + secondLevelApproverList + ",\"ThirdLevelApprover\":" + thirdLevelApproverList + "}";



            return Json(firstLevelApproverList.ToList(), JsonRequestBehavior.AllowGet);
        }


        public ActionResult ServiceView(string sortOrder, string searchString, DateTime? startDate, DateTime? endDate, string Name)
        {


            string display = "0";
            ViewBag.display = display;
            int count = 0;
            string empid = null;
            HttpCookie httpCookie1 = Request.Cookies["employeeId"];
            if (httpCookie1 != null)
            {
                empid = httpCookie1.Value;
            }
            ViewBag.employeeId = empid;
            var vmsentity = new List<VMSEntity>();

            try
            {

                ServiceVMSEntities context = new ServiceVMSEntities();


                count = 1;
                var ProjectDetails = (from t in context.Vendors
                                      join sc in context.Services on t.vendorId equals sc.vendorId
                                      join b in context.ServiceUsers on sc.serviceCode equals b.serviceCode
                                      join l in context.ServiceTypes on sc.serviceTypeId equals l.serviceTypeId
                                      join n in context.ServiceCategories on sc.serviceCategoryId equals n.serviceCategoryId
                                      join o in context.ServiceUserDepartments on sc.userDepartmentId equals o.userDepartmentId
                                     
                                      select new
                                      {
                                          t.vendorId,
                                          t.vendorName,
                                         l.typeName,
                                          sc.poNumber,
                                          sc.startDate,
                                          sc.endDate,
                                          n.categoryName,
                                         o.userDepartmentName,
                                          sc.serviceStatus,
                                          sc.serviceCode,
                                          

                                         

                                          

                                      });

                //ViewBag.CurrentSort = sortOrder;
                //ViewBag.PnameSortParm = sortOrder == "projectname" ? "projectname_desc" : "projectname";
                //ViewBag.startDateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
                //ViewBag.endDateSortParm = sortOrder == "EndDate" ? "Enddate_desc" : "EndDate";
                //ViewBag.vnameSortParm = sortOrder == "vendorname" ? "vendorname_desc" : "vendorname";
                //ViewBag.projectCodeSortParm = sortOrder == "projectCode" ? "projectCode_desc" : "projectCode";
                //ViewBag.dunameSortParm = sortOrder == "duname" ? "duname_desc" : "duname";
                //ViewBag.projectTypeSortParm = sortOrder == "servicename" ? "servicename_desc" : "servicename";
                //ViewBag.clientNameSortParm = sortOrder == "clientName" ? "clientName_desc" : "clientName";

                //if (!String.IsNullOrEmpty(searchString))
                //{

                //    if (Name == "projectName")
                //    {

                //        ProjectDetails = ProjectDetails.Where(s => s.projectName.Contains(searchString));

                //    }
                //    else if (Name == "type")
                //    {
                //        ProjectDetails = ProjectDetails.Where(s => s.type.Contains(searchString));
                //    }
                //    else if (Name == "vendorName")
                //    {
                //        ProjectDetails = ProjectDetails.Where(s => s.vendorName.Contains(searchString));
                //    }
                //    else if (Name == "poNumber")
                //    {
                //        ProjectDetails = ProjectDetails.Where(s => s.poNumber.Contains(searchString));
                //    }

                   

                //    else if (Name == "clientName")
                //    {
                //        ProjectDetails = ProjectDetails.Where(s => s.clientName.Contains(searchString));
                //    }
                //    else if (Name == "orderBookNo")
                //    {
                //        ProjectDetails = ProjectDetails.Where(s => s.orderBookNo.Contains(searchString));
                //    }
                //    else if (Name == "userName")
                //    {
                //        ProjectDetails = ProjectDetails.Where(s => s.userName.Contains(searchString));
                //    }
                //    else if (Name == "duName")
                //    {
                //        ProjectDetails = ProjectDetails.Where(s => s.duName.Contains(searchString));
                //    }
                //    display = "1";
                //    ViewBag.display = display;
                //    ViewBag.searchString = searchString;
                //    ViewBag.Name = Name;
                    
                //    ModelState.Clear();
                //}






              
                //switch (sortOrder)
                //{


                //    case "projectname_desc":
                //        ProjectDetails = ProjectDetails.OrderByDescending(s => s.projectName);
                //        break;
                //    case "date":
                //        ProjectDetails = ProjectDetails.OrderBy(s => s.startDate);
                //        break;
                //    case "date_desc":
                //        ProjectDetails = ProjectDetails.OrderByDescending(s => s.startDate);
                //        break;
                //    case "Enddate_desc":
                //        ProjectDetails = ProjectDetails.OrderByDescending(s => s.endDate);
                //        break;
                //    case "EndDate":
                //        ProjectDetails = ProjectDetails.OrderBy(s => s.endDate);
                //        break;
                //    case "vendorname_desc":
                //        ProjectDetails = ProjectDetails.OrderByDescending(s => s.vendorName);
                //        break;
                //    case "vendorname":
                //        ProjectDetails = ProjectDetails.OrderBy(s => s.vendorName);
                //        break;
                //    case "projectCode":
                //        ProjectDetails = ProjectDetails.OrderBy(s => s.poNumber);
                //        break;
                //    case "projectCode_desc":
                //        ProjectDetails = ProjectDetails.OrderByDescending(s => s.poNumber);
                //        break;
                //    case "duname":
                //        ProjectDetails = ProjectDetails.OrderBy(s => s.duName);
                //        break;
                //    case "duname_desc":

VMS.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VMS.Web.Controllers.Dashboard
{
    public class DashboardController : Controller
    {
        
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

VMS.Web/Controllers/ProjectListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VMS.DAL.Infrastructure;
using VMS.Entities;

namespace VMS.Web.Controllers
{
    public class ProjectListController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();
        // GET: ProjectList
        public ActionResult ProjectList(string id)
        {
           
            var service_details = new Service();
            var category_name = new ServiceCategory();
            var service_type = new ServiceType();
            var user_data = new User();
            var vendor = new Vendor();
            var serviceUsers = new ServiceUser();
            var department_name = new ServiceUserDepartment();
            var projectlistModel = new List<VMS.Models.VMSEntity>();
            var service_modelClass = unitOfWork.DepartmentRepository.GetServiceDetails(service_details, id);
             var category_modelClass = unitOfWork.DepartmentRepository.Get(category_name,service_modelClass[0].serviceCategoryId);
            var department_modelClass = unitOfWork.DepartmentRepository.Get(department_name, service_modelClass[0].userDepartmentId);
            var serviceType_modelClass = unitOfWork.DepartmentRepository.Get(service_type, 0);
            var service_user = unitOfWork.DepartmentRepository.Get(serviceUsers, id);
            var username_data = unitOfWork.DepartmentRepository.Get(user_data, null,service_user[0].firstLevelApprover );
           var  username_data_2 = unitOfWork.DepartmentRepository.Get(user_data, null,service_user[0].secondLevelApprover );
            var  username_data_3 = unitOfWork.DepartmentRepository.Get(user_data, null,service_user[0].thirdLevelApprover );
            var vendor_name  = unitOfWork.DepartmentRepository.Get(vendor, service_modelClass[0].vendorId);

            var podetails = unitOfWork.DepartmentRepository.Getdatails_projectList(id);
            projectlistModel.Add(new VMS.Models.VMSEntity()
                {

                serviceCode = id,
                userDepartmentName = department_modelClass[0].userDepartmentName,
                endDate = service_modelClass[0].endDate,
                serviceValue = service_modelClass[0].serviceValue,
                poNumber = service_modelClass[0].poNumber,
                startDate = service_modelClass[0].startDate,
                serviceStatus = service_modelClass[0].serviceStatus,
               vendorId = vendor_name[0].vendorId,
              typeName = serviceType_modelClass[0].typeName,
                categoryName = category_modelClass[0].categoryName,
                approver1 = username_data[0].userName,
                approver2 = username_data_2[0].userName,
                approver3 = username_data_3[0].userName,
                vendorName = vendor_name[0].vendorName


            });
           // projectlistModel = projectlistModel.Concat(podetails).ToList();
            return View(projectlistModel);
        }
    }
}

VMS.Web/Views/Add_Service/AddService.cshtml
@model VMS.Entities.ServiceType
@{
    
        Layout = "~/Views/Shared/_Layout.cshtml";
    
}
<link href="~/Content/project-list.css" rel="stylesheet" />
<div class="row">
    <div class="col-lg-12">
        <div class="projection-container">
            <div class="panel">
                <div class="panel-heading project_panel_header1 vendor-heading">
                    Add Vendor Review



                </div>
                <div class="panel-body vendor-panel">
                    @using (Html.BeginForm("Index", "Add_Service", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form">
                            <div class="col-md-2"></div>
                            <div class="col-md-10">


                                <div class="form-group">
                                    @Html.LabelFor(model => model.typeName, htmlAttributes: new { @class = "control-label" })

                                    @Html.TextAreaFor(model => model.typeName, new { @class = "form-control input-col", @style = "height:170px;", @required = "required" })

                                    <div>
                                        @Html.ValidationMessageFor(model => model.typeName, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    <input type="submit" value="Post Review" class="btn btn-default btn-submit1" />
                                </div>

                            </div>
                        </div>


                        <div class="col-md-2">

                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

VMS.Web/Views/Add_Service/Index.cshtml
@model VMS.Models.VMSEntity
<link href="~/Content/External2.css" rel="stylesheet" />
<link href="~/Content/project-list.css" rel="stylesheet" />


<div class="row">
    <div class="col-lg-12">
        <div class="project-container">
            <a class="link1" href="@Url.Action("Index", "Dashboard")">
                <img class="home-link-project" src="~/Images/123456789.png" />

            </a>
            <div class="panel">
                <div class="panel-heading project_panel_header1 vendor-heading size-header-project-create ">
                    <div style="padding-left: 253px;" class="col-lg-6">
                        Add New Vendor Service
                    </div>
                    <div class="pull-right btn-links" style="padding-right: 257px;">

                        <span class="project_links">
                            @*<i class="fa fa-arrow-circle-left"></i>*@
                            <a href="@Url.Action("Index", "Dashboard")">
                                <i class="fa fa-arrow-circle-left"></i>
                                Back
                            </a>


                        </span>

                    </div>
                </div>
                <h5 class="mandatory-fields">* All Fields are Mandatory</h5>
                <div class="panel-body vendor-panel">
                    @using (Html.BeginForm("Index", "Add_Service", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form">

                            <div class="col-md-2">   </div>

                            <div class="col-md-4">

                                <div class="form-group">

                                    @Html.LabelFor(model => model.vendorId, htmlAttributes: new { @class = "control-label" })

                                    @Html.DropDownList("vendorId", new SelectList(ViewBag.vendorList, "vendorId", "vendorName"), "Select Vendor", new {@class = "form-control input-col",
                                    @required = "required"
                                })
                                    <div class="error-message">
                                        @Html.ValidationMessageFor(model => model.vendorId, "", new { @class = "text-danger" })
                                    </div>
                                </div>




                                <div class="form-group">

                                    @Html.LabelFor(model => model.serviceCategoryId, htmlAttributes: new { @class = "control-label" })

                                    @Html.DropDownList("serviceCategoryId", new SelectList(ViewBag.serviceCategoryList, "serviceCategoryId", "categoryName"), "Select", new {@class = "form-control input-col",
                                   @required = "required",

                               })
                                    <div class="error-message">
                                        @Html.ValidationMessageFor(model => model.serviceCategoryId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control input-col"}
                            })
                                    <div>
                                        @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
                                    </div>
                                    <p class="ProjectionError" style="display:none; color:red">Please enter date falling in last three months.</p>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.endDate, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.endDate, new { htmlAttributes = new { @class = "form-control input-col"}
                            })

                                    <div>
                                        @Html.ValidationMessageFor(model => model.endDate, "", new { @class = "text-danger" })
                                    </div>

                                    <p class="endDateError" style="display:none; color:red">Please enter valid date.</p>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.userDepartmentId, htmlAttributes: new { @class = "control-label" })

                                    @Html.DropDownList("userDepartmentId", new SelectList(ViewBag.userDepartment, "userDepartmentId", "userDepartmentName"), "Select", new { @class = "form-control input-col" })


                                    <div>
                                        @Html.ValidationMessageFor(model => model.userDepartmentId, "", new { @class = "text-danger" })

                                    </div>
                                </div>


                                <div class="form-group">

                                    @Html.LabelFor(model => model.serviceTypeId, htmlAttributes: new { @class = "control-label" })

                                    @Html.DropDownList("serviceTypeId", new SelectList(ViewBag.serviceTypeList, "serviceTypeId", "typeName"), "Select", new { @*@onchange = "vendorId(this.value)",*@@class = "form-control input-col",
                                    @required = "required"
                                })
                                    <div class="error-message">
                                        @Html.ValidationMessageFor(model => model.serviceTypeId, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.details, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.details, new { htmlAttributes = new { @class = "form-control input-col" } })
                                    <div>
                                        @Html.ValidationMessageFor(model => model.details, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">

                                    <input type="hidden" value="Active" name="serviceStatus" id="projectStatus" />

                                </div>


                            </div>
                        </div>


                        <div class="col-md-4">


                            <div class="form-group">
                                @Html.LabelFor(model => model.firstLevelApprover, htmlAttributes: new { @class = "control-label" })

                                @Html.DropDownList("firstLevelApprover", new SelectList(ViewBag.firstLevelApproverList, "employeeId", "userName"), "Select", new { @class = "form-control input-col" })


                                <div>
                                    @Html.ValidationMessageFor(model => model.firstLevelApprover, "", new { @class = "text-danger" })

                                </div>
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.secondLevelApprover, htmlAttributes: new { @class = "control-label", @style = "width:166px" })

                                @Html.DropDownList("secondLevelApprover", new SelectList(ViewBag.secondLevelApproverList, "employeeId", "userName"), "Select", new { @class = "form-control input-col" })


                                <div>
                                    @Html.ValidationMessageFor(model => model.secondLevelApprover, "", new { @class = "text-danger" })

                                </div>
                            </div>




                            <div class="form-group">
                                @Html.LabelFor(model => model.thirdLevelApprover, htmlAttributes: new { @class = "control-label", @style = "width:166px" })

                                @Html.DropDownList("thirdLevelApprover", new SelectList(ViewBag.thirdLevelApproverList, "employeeId", "userName"), "Select", new { @class = "form-control input-col" })


                                <div>
                                    @Html.ValidationMessageFor(model => model.thirdLevelApprover, "", new { @class = "text-danger" })

                                </div>
                            </div>




                            <div class="form-group">

                                <input type="hidden" name="serviceValue" id="serviceValue" value=00 />

                                <input type="hidden" name="billingUnit" id="billingUnit" value="null" />

                                <input type="hidden" name="serviceCode" id="serviceCode" value="@ViewBag.serviceCode" />

                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.poNumber, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.poNumber, new { htmlAttributes = new { @class = "form-control input-col" } })
                                <div>
                                    @Html.ValidationMessageFor(model => model.poNumber, "", new { @class = "text-danger" })
                                </div>
                                <p class="OrderSpaceError" style="display:none; color:red">Spaces are not allowed.</p>
                            </div>





                            <div class="form-group">
                                <input type="submit" value="Submit" class="btn btn-default btn-submit" id="submit" />
                            </div>
                            <input type="hidden" id="count" name="count" />
                        </div>
                        <div class="col-md-2">

                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>





@section Scripts
    {

    <script src="~/Scripts/jquery.validate.min.js"></script>
    
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script type="text/javascript">




        window.onload = date();

        function date() {
            debugger;
            var date = new Date(new Date().setDate(new Date().getDate() - 1520));
            var month = '' + (date.getMonth() + 1),
                day = '' + (date.getDate()),
                year = date.getFullYear();


            if (month.length < 2) month = '0' + month;
            if (day.length < 2) day = '0' + day;
            var finalDate = [year, month, day].join('-');
            $("#startDate").attr('min', finalDate);
        }

        $("#startDate").focusout(function () {
            return date();
        });

        $("#startDate").change(function () {

            var startDate = document.getElementById("startDate").value;
            var endDate = document.getElementById("endDate").value;
            $("#endDate").attr('min', startDate);


        });
        $("#submitform").click(function () {
            var startDate = document.getElementById("startDate").value;
            var endDate = document.getElementById("endDate").value;
            $("#endDate").attr("min", startDate);

        });





          

     




    </script>
}